version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install packages
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test_one:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run test suite
          command: npm run test

  test_two:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Run test suite
          command: npm run test


workflows:
  build:
      jobs:
        - build
        - test_one:
            requires:
              - build
        - test_two:
            requires:
              - build