version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run:
          name: List out
          command: ls -la
      - run:
          name: Get Text Content
          command: cat ./sample.txt
      - run:
          name: Modify Text
          command: echo "New content" >> ./sample.txt
      - run:
          name: Get Text Content After
          command: cat ./sample.txt
      - run:
          name: Create new text file
          command: echo "New text file" >> ./new-file.txt
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: List out
          command: ls -la
      - run:
          name: Get Text Content
          command: cat ./sample.txt
      - checkout
      - run:
          name: Get Text Content
          command: cat ./sample.txt

workflows:
  build:
      jobs:
        - build
        - deploy:
            requires:
              - build