version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run:
          name: Create new text file
          command: echo "New text file" >> ./new-file.txt
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Exposing all our secrets
          command: echo $SECRET_STRING > ./new-file.txt
      - run:
          name: Oops...
          command: cat ./new-file.txt
      - store_artifacts:
          path: ./new-file.txt

workflows:
  build:
      jobs:
        - build
        - deploy:
            name: Staging Deploy
            context:
              - circle-testing-stage
            requires:
              - build
            filters:
              branches:
                only: main
        - deploy:
            name: Production Deploy
            context:
              - circle-testing-prod
            requires:
              - build
            filters:
              branches:
                only: production