version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run:
          name: Create new text file
          command: echo "New text file" >> ./new-file.txt
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Deploy"
          command: cat ./new-file.txt
      - store_artifacts:
          path: ./new-file.txt

workflows:
  release-branch-workflow:
    jobs:
      - build
      - request-testing:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - request-testing